services:
  authorizathion:
    build: ./service
    container_name: auth-server
    ports:
      - 8080:8080
    environment:
      GIN_MODE: "release"
      SERVER_ADDRESS: "0.0.0.0:8080"
      SERVER_PASSWORD: "jwt-secret"
      POSTGRES_ADDRESS: "postgres:5432"
      POSTGRES_USER: "system"
      POSTGRES_PASSWORD: "system"
      POSTGRES_DB: "authorizathion"
    depends_on:
      - postgres

  postgres:
    image: postgres:17
    container_name: auth-postgres
    command: ["postgres", "-c", "logging_collector=off", "-c", "log_statement=none"]
    restart: always
    environment:
      POSTGRES_USER: "system"
      POSTGRES_PASSWORD: "system"
      POSTGRES_DB: "authorizathion"
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data: